---
- name: Playbook to install apache
  hosts: all
  become: true
  tasks:

    - name: Ensure to install apache
      dnf:
        name: httpd
        state: latest


    - name: 2 - Ensure to start apache
      system:
        name: httpd
        state: restarted
